- name: install build tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - checkinstall
    - apt-utils
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - gcc
