- name: setup locale
  become: yes
  script: setup-locales.sh

- name: setup timezone data
  become: yes
  shell: echo 'Europe/Oslo' > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata


- name: remove PAM wrong password delay low-limit
  become: yes
  command: sed -i 's/pam_unix.so nullok_secure$/pam_unix.so nullok_secure nodelay/g' /etc/pam.d/common-auth

- name: set PAM wrong password delay to 0.5 seconds
  become: yes
  command: sed -i 's/delay=[0-9]\+/delay=500000/g' /etc/pam.d/login

- name: install core system/build tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - software-properties-common
    - apt-utils
    - checkinstall
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - gcc

- name: install core shell tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - curl
    - htop
    - bzip2
    - wget
    - python
    - python-pip
    - tree
    - subversion

- include: git.yml
- include: ruby.yml

- name: link configs
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
    force: yes
  with_items:
    - .bashrc




