- name: setup locale
  become: yes
  script: setup-locales.sh

- name: setup timezone data
  become: yes
  shell: echo 'Europe/Oslo' > /etc/timezone && dpkg-reconfigure tzdata -f noninteractive

- name: add universe repository
  become: yes
  apt_repository: repo="universe"

- name: install core system/build tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - software-properties-common
    - apt-utils
    - checkinstall
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - gcc

- name: install core shell tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - curl
    - bzip2
    - wget
    - python
    - python-pip

- include: git.yml
- include: ruby.yml

- name: link configs
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
    force: yes
  with_items:
    - .bashrc




