- include: locale.yml
- include: build-tools.yml
- include: git.yml

- name: install core packages
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - silversearcher-ag
    - curl
    - bzip2
    - wget
    - software-properties-common
    - python
    - python-pip
    - ruby

- include: tmux.yml

- name: link configs
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
    force: yes
  with_items:
    - .agignore
    - .bashrc


