- include: locale.yml
- include: build-tools.yml
- include: git.yml

- name: install core packages
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - curl
    - bzip2
    - wget
    - software-properties-common
    - python
    - python-pip
    - ruby

- include: tmux.yml

