#!/bin/bash


if ! command -v ansible-playbook > /dev/null; then
  sudo apt-add-repository ppa:ansible/ansible
  sudo apt-get update
  sudo apt-get install ansible
fi


CWD="$(dirname "$(readlink -f "$0")")"
# ansible-playbook vagrant-playbook.yml -i hosts -u vagrant --ask-sudo-pass --private-key=~/.vagrant.d/insecure_private_key -l vagrant -U vagrant
# ansible-playbook "$CWD/vagrant-playbook.yml" -i "$CWD/hosts" -l localhost -vvv "$@"
ansible-playbook "$CWD/vagrant-playbook.yml" -i "$CWD/hosts" -l localhost -v "$@"
