#!/bin/bash

# ansible-playbook vagrant-playbook.yml -i hosts -u vagrant --ask-sudo-pass --private-key=~/.vagrant.d/insecure_private_key -l vagrant -U vagrant
ansible-playbook vagrant-playbook.yml -i hosts -u vagrant --private-key=~/.vagrant.d/insecure_private_key -l vagrant -U vagrant -vvv
