---
- hosts: vagrant
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - { role: core, tags: [ core ] }
    - { role: tools, tags: [ tools ] }
    - { role: zsh, tags: [ shell, zsh ] }
    - { role: neovim, tags: [ editor, vim, neovim ] }
    - { role: tmux, tags: [ tools, tmux ] }
    - { role: profanity, tags: [ chat, profanity ] }
    - { role: i3, tags: [ desktop, i3 ] }
    - { role: mail, tags: [ mail, mutt ] }
    - { role: fonts, tags: [ fonts ] }
    - { role: development, tags: [ development ] }

