#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if needs_install ncmpcpp; then
  # ruby support (vim-nox)
  apt_install vim-nox
else
  debug "vim is already installed"
fi

symlink_to_home "$CWD/.vim"
