---
- name: install various useful command-line tools
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - feh
    - scrot
    - silversearcher-ag

- name: update fzf
  git: repo="https://github.com/junegunn/fzf.git" dest="{{user_home}}/.fzf" depth=1 update=yes

- name: install fzf
  command: "{{user_home}}/.fzf/install"

- name: link configs
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
    force: yes
  with_items:
    - .agignore
