#!/bin/bash

set -e

if command -v castnow &>/dev/null; then
  echo "castnow already installed"
  which castnow
  exit
fi

if ! command -v npm &>/dev/null; then
  ./nodejs-setup
fi

sudo npm install castnow -g
