#!/bin/bash

set -e

DOTFILE_ROOT="$(pwd)"
if [ "$DOTFILE_ROOT" != "$HOME/dotfiles" ]; then
  echo "must be run from $HOME/dotfiles"
  exit 1
fi
ln -fs "$DOTFILE_ROOT/.aliases" "$HOME"
ln -fs "$DOTFILE_ROOT/.variables" "$HOME"
ln -fs "$DOTFILE_ROOT/.functions" "$HOME"
source "$HOME/.functions"
cmdpid "Xorg"
./scripts/installation/git/install

git submodule update --init

exit
./scripts/installation/vim/install
./zsh-setup
./tmux-setup

ln -fs "$DOTFILE_ROOT/bin" "$HOME"
ln -fs "$DOTFILE_ROOT/.gemrc" "$HOME"
ln -fs "$DOTFILE_ROOT/.my.cnf" "$HOME"
ln -fs "$DOTFILE_ROOT/.notify-osd" "$HOME"
ln -fs "$DOTFILE_ROOT/.asoundrc" "$HOME"
ln -fs "$DOTFILE_ROOT/.xinitrc" "$HOME"
ln -fs "$DOTFILE_ROOT/.Xresources" "$HOME"
ln -fs "$DOTFILE_ROOT/.urxvt" "$HOME"



# warn about missing packages

# linter packages

# bash
[[ -z "$(which shellcheck)" ]] && echo "sudo apt-get install shellcheck" || echo "shellcheck installed"
[[ -z "$(which bashate)" ]] && echo "sudo apt-get install python-pip && sudo pip install bashate" || echo "bashate installed"
# markdown
[[ -z "$(which mdl)" ]] && echo "sudo gem install mdl" || echo "mdl installed"
# pylint
[[ -z "$(which pylint)" ]] && echo "sudo pip install pylint" || echo "pylint installed"


# various other tools
[[ -z "$(which feh)" ]] && echo "sudo apt-get install feh" || echo "feh installed"
[[ -z "$(which scrot)" ]] && echo "sudo apt-get install scrot" || echo "scrot installed"
[[ -z "$(which unclutter)" ]] && echo "sudo apt-get install unclutter" || echo "unclutter installed"
