version: '2'
services:
  base:
    build: ./docker/base/
    container_name: dotfiles-base
  test:
    image: dotfiles_base
    container_name: dotfiles-test
    hostname: dotfiles-test
    working_dir: /home/kalvatn/dotfiles
    user: kalvatn
    command: sudo -iu kalvatn bash -l
    environment:
      TERM: 'screen-256color'
      DEBIAN_FRONTEND: noninteractive
    depends_on:
      - base
    volumes:
      - .:/home/kalvatn/dotfiles
