#!/bin/bash


# install i3blocks
if command -v i3blocks &> /dev/null;then
  echo "i3blocks is already installed"
else
  sudo apt-get install ruby-ronn
  cd /tmp
  git clone git://github.com/vivien/i3blocks
  cd i3blocks
  make clean all
  sudo make install
fi

grep "workspace \$workspace_\d" "$HOME/.i3/config"
# find monitors
connected_outputs="$(xrandr -q | grep -w connected | cut -d ' ' -f1)"
if [ "$(echo "$connected_outputs" | wc -l)" -gt 1 ]; then
  echo "more than one connected outputs : $connected_outputs"
else
  echo "only one connected output : $connected_outputs"
fi
