#!/bin/bash


# install i3blocks
if command -v i3blocks &> /dev/null;then
  echo "i3blocks is already installed"
else
  sudo apt-get install ruby-ronn
  cd /tmp
  git clone git://github.com/vivien/i3blocks
  cd i3blocks
  make clean all
  sudo make install
fi

# find monitors
outputs="$(xrandr -q | grep connected | cut -d ' ' -f1)"
if [ "$(echo "$outputs" | wc -l)" -gt 1 ]; then
  echo "$outputs"
fi
