#!/bin/bash

set -e

# https://launchpad.net/~hanipouspilot/+archive/ubuntu/rtlwifi
if [ -f /etc/apt/sources.list.d/hanipouspilot-rtlwifi-trusty.list ]; then
  echo "hanipouspilot-rtlwifi list already added"
else
  echo "adding /etc/apt/sources.list.d/hanipouspilot-rtlwifi-trusty.list"
  sudo add-apt-repository ppa:hanipouspilot/rtlwifi
  echo "updating packages (quiet)"
  sudo apt-get update -qq
fi

sudo apt-get install dkms rtlwifi-new-dkms

echo "reboot to apply changes"
