#!/bin/bash

set -e

if sudo apt-key list | grep mopidy &> /dev/null; then
  echo "mopidy gpg already added"
else
  echo "adding mopidy gpg key"
  wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
fi

if [ -f /etc/apt/sources.list.d/mopidy.list ]; then
  echo "mopidy list already added"
else
  echo "adding /etc/apt/sources.list.d/mopidy.list"
  sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/mopidy.list
fi

echo "updating packages (quiet)"
#sudo apt-get update -qq


sudo apt-get install mopidy mopidy-alsamixer mopidy-spotify mopidy-spotify-tunigo mopidy-scrobbler ncmpcpp
#sudo pip install Mopidy-Mopify

MOPIDY_CONF="$HOME/.config/mopidy/mopidy.conf"

read -p "spotify username: " username
read -sp "spotify password: " password

printf "\n"

sudo sed -i "s/SPOTIFY_PASSWORD/$password/g" "$MOPIDY_CONF"
sudo sed -i "s/SPOTIFY_USERNAME/$username/g" "$MOPIDY_CONF"

read -p "lastfm username: " username
read -sp "lastfm password: " password

printf "\n"

sudo sed -i "s/LASTFM_PASSWORD/$password/g" "$MOPIDY_CONF"
sudo sed -i "s/LASTFM_USERNAME/$username/g" "$MOPIDY_CONF"


