#!/bin/bash

set -e

git submodule update --init
cwd=$(pwd)
ln -fs "$cwd/.vim" "$HOME"
ln -fs "$cwd/.gitconfig" "$HOME"
ln -fs "$cwd/.gitignore_global" "$HOME"
ln -fs "$cwd/.vim/.vimrc" "$HOME"
ln -fs "$cwd/.tmux.conf" "$HOME"
ln -fs "$cwd/.zshrc" "$HOME"
ln -fs "$cwd/.oh-my-zsh" "$HOME"
ln -fs "$cwd/oh-my-zsh-custom-themes/kalvatn.zsh-theme" "$HOME/.oh-my-zsh/themes/"
