#!/bin/bash

set -e

git submodule update --init
cwd=$(pwd)
ln -fs "$cwd/bin" "$HOME"
ln -fs "$cwd/.vim" "$HOME"
ln -fs "$cwd/.vim/.vimrc" "$HOME"
ln -fs "$cwd/.gitconfig" "$HOME"
ln -fs "$cwd/.gitignore_global" "$HOME"
ln -fs "$cwd/.tmux.conf" "$HOME"
ln -fs "$cwd/.zshrc" "$HOME"
ln -fs "$cwd/.oh-my-zsh" "$HOME"
ln -fs "$cwd/oh-my-zsh-custom-themes/kalvatn.zsh-theme" "$HOME/.oh-my-zsh/themes/"
ln -fs "$cwd/.aliases" "$HOME"
ln -fs "$cwd/.gemrc" "$HOME"
ln -fs "$cwd/.my.cnf" "$HOME"

# i3
ln -fs "$cwd/.i3" "$HOME"

# warn about missing packages

# linter packages

# bash
[[ -z "$(which shellcheck)" ]] && echo "sudo apt-get install shellcheck" || echo "shellcheck installed"
[[ -z "$(which bashate)" ]] && echo "sudo apt-get install python-pip && sudo pip install bashate" || echo "bashate installed"
# markdown
[[ -z "$(which mdl)" ]] && echo "sudo gem install mdl" || echo "mdl installed"
# pylint
[[ -z "$(which pylint)" ]] && echo "sudo pip install pylint" || echo "pylint installed"


# various other tools
[[ -z "$(which feh)" ]] && echo "sudo apt-get install feh" || echo "feh installed"
[[ -z "$(which scrot)" ]] && echo "sudo apt-get install scrot" || echo "scrot installed"
[[ -z "$(which unclutter)" ]] && echo "sudo apt-get install unclutter" || echo "unclutter installed"
