#!/bin/bash

set -e

sudo apt-get install zsh

cwd=$(pwd)
ln -fs "$cwd/.zshrc" "$HOME"
ln -fs "$cwd/.oh-my-zsh" "$HOME"
ln -fs "$cwd/oh-my-zsh-custom-themes/kalvatn.zsh-theme" "$HOME/.oh-my-zsh/themes/"

echo "running chsh -s /bin/zsh"
chsh -s /bin/zsh
