#!/bin/bash

set -e

source "$HOME/.functions"

if needs_install vim vim-nox; then
  # vim with +ruby support
  apt_install vim-nox
fi

CWD="$(get_script_dir "$0")"
symlink_to_home "$CWD/.vim"
symlink_to_home "$CWD/.vim/.vimrc"
