#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if ! command_exists vim; then
  # ruby support (vim-nox), clipboard support (vim-gtk)
  apt_install vim-nox vim-gtk
else
  debug "vim is already installed"
fi

symlink_to_home "$CWD/.vim"
