#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if needs_install xmllint libxml2-utils; then
  info "installing libxml2-utils"
  apt_install libxml2-utils
else
  debug "xmllint already installed"
fi
