#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if needs_install profanity; then
  #curl -s -L "https://raw.githubusercontent.com/boothj5/profanity/master/install-all.sh" | sudo -E bash -
  git clone https://github.com/boothj5/profanity.git /tmp/profanity
  cd /tmp/profanity
  sudo ./install-all.sh
  if [ -d "$HOME/.config/profanity" ]; then
    info "removing default config"
    rm -Rf "$HOME/.config/profanity"
  fi
fi

if needs_install secret-tool libsecret-tools; then
  apt_install libsecret-tools
fi

mkdir -p "$HOME/.config"
symlink "$CWD/.config/profanity" "$HOME/.config/"

if [ -t 1 -a ! -z "$DISPLAY" ]; then
  ACCOUNT="j.kalvatn@jabberd.betradar.com"
  if ! secret-tool lookup xmpp "$ACCOUNT" &> /dev/null; then
    info "storing password for $ACCOUNT"
    secret-tool store --label "$ACCOUNT" xmpp "$ACCOUNT"

    info "copy paste in profanity client : /account set $ACCOUNT eval_password \"secret-tool lookup xmpp $ACCOUNT\""
  else
    info "copy paste in profanity client : /account set $ACCOUNT eval_password \"secret-tool lookup xmpp $ACCOUNT\""
  fi
fi

