#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if needs_install nvim neovim python-dev python-pip python3-dev python3-pip; then
  apt_add_repository "ppa:neovim-ppa/unstable"
  apt_install neovim python-dev python-pip python3-dev python3-pip
fi

symlink "$CWD/.config/nvim" "$HOME/.config"
