#!/bin/bash

set -e

DICT_DIR=/usr/share/stardict/dic
TMP_DICT_DIR=/tmp/dicts

# http://askubuntu.com/questions/191125/is-there-an-offline-command-line-dictionary

# stardict console version (http://sdcv.sourceforge.net/)
sudo apt-get install sdcv

if [ -d "$DICT_DIR" ]; then
  echo "$DICT_DIR already exists"
else
  sudo mkdir -p "$DICT_DIR"
fi

if [ -d "$TMP_DICT_DIR" ]; then
  echo "$TMP_DICT_DIR already exists"
else
  mkdir -p "$TMP_DICT_DIR"
fi

# download dictionaries

# CIDE (https://en.wikipedia.org/wiki/Collaborative_International_Dictionary_of_English)
if [ -f "$TMP_DICT_DIR/cide.tar.bz2" ]; then
  echo "CIDE dict already installed"
else
  echo "downloading CIDE dict"
  curl -L "https://web.archive.org/web/20140917131745/http://abloz.com/huzheng/stardict-dic/dict.org/stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2" -o "$TMP_DICT_DIR/cide.tar.bz2"
  sudo tar xvjf "$TMP_DICT_DIR/cide.tar.bz2" -C "$DICT_DIR"
fi

# GNU Linux English-English
if [ -f "$TMP_DICT_DIR/gnu-linux.tar.bz2" ]; then
  echo "GNU Linux English-English dict already installed"
else
  echo "downloading CIDE dict"
  curl -L "http://abloz.com/huzheng/stardict-dic/misc/stardict-xfardic-gnu-linux-2.4.2.tar.bz2" -o "$TMP_DICT_DIR/gnu-linux.tar.bz2"
  sudo tar xvjf "$TMP_DICT_DIR/gnu-linux.tar.bz2" -C "$DICT_DIR"
fi
