#!/bin/bash

set -e

if ! sudo apt-key list | grep docker &> /dev/null; then
  echo "adding docker gpg key"
  curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
fi

if ! command -v docker &> /dev/null; then
  echo "installing docker"
  sudo apt-get install curl
  curl -fsSL https://get.docker.com/ | sh
fi

if ! groups kalvatn | grep docker &> /dev/null; then
  echo "adding kalvatn to docker group, requires relog"
  sudo usermod -aG docker kalvatn
fi
docker run hello-world

echo "https://docs.docker.com/linux/"

#cwd=$(pwd)

#ln -fs "$cwd/.vim" "$HOME"
#ln -fs "$cwd/.vim/.vimrc" "$HOME"
