- name: add neovim repository
  become: yes
  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: install dependencies
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - silversearcher-ag
    - xsel
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - ruby

- name: install python2 pip package
  become: yes
  pip: name=neovim executable=pip2

- name: install python3 pip package
  become: yes
  pip: name=neovim executable=pip3

- name: install neovim
  become: yes
  apt: pkg=neovim state=latest

- name: install dein plugin manager
  shell: curl -s -L https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s "{{user_home}}/.config/nvim/dein"

- name: configure neovim alternatives
  become: yes
  alternatives: name="{{item}}" path=/usr/bin/nvim
  with_items:
    - vi
    - vim
    - editor


- name: link configuration
  file:
    src: "{{role_path}}/files/nvim/{{item}}"
    dest: "{{user_home}}/.config/nvim/{{item}}"
    state: link
  with_items:
    - init.vim
    - vimdiff.vim

- name: run dein#update()
  command: vim +"call dein#update()" +"qall" --headless
