- name: add neovim repository
  become: yes
  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: install dependencies
  become: yes
  apt: pkg="{{item}}" state=latest
  with_items:
    - silversearcher-ag
    - xsel
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - ruby

- name: install python2 pip package
  become: yes
  pip: name=neovim executable=pip2

- name: install python3 pip package
  become: yes
  pip: name=neovim executable=pip3

- name: install neovim
  become: yes
  apt: pkg=neovim state=latest

- name: install dein plugin manager
  shell: curl -s -L https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s "{{user_home}}/.config/nvim/dein"

- name: setup neovim alternatives
  become: yes
  shell: update-alternatives --install "/usr/bin/{{item}}" "{{item}}" /usr/bin/nvim 60 && update-alternatives --config "{{item}}"
  with_items:
    - vi
    - vim
    - editor

- name: link configuration
  file:
    src: "{{role_path}}/files/nvim/init.vim"
    dest: "{{user_home}}/.config/nvim/init.vim"
    state: link
