#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

BASHRC="$HOME/.bashrc"
ZSHRC="$HOME/.zshrc"

if needs_install tmux; then
  apt_install tmux
fi

if needs_install tmuxinator; then
  gem_install tmuxinator
  tmuxinator doctor
  if [ -d "$HOME/.tmuxinator" ]; then
    info "removing default config"
    rmdir "$HOME/.tmuxinator"
  fi
fi

if [ ! -d "$CWD/.tmuxinator" ]; then
  info "creating empty $CWD/.tmuxinator directory"
  mkdir -p "$CWD/.tmuxinator"
fi


function source_completion_file() {
  target_dir="$CWD/.tmuxinator/completion"
  mkdir -p "$target_dir"

  if [ "$1" == "$BASHRC" ]; then
    target_filename="tmuxinator.bash"
  elif [ "$1" == "$ZSHRC" ]; then
    target_filename="tmuxinator.zsh"
  fi

  if [ ! -f "$target_dir/$target_filename" ]; then
    url="https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/$target_filename"
    info "downloading $target_filename completion file"
    curl "$url" -o "$target_dir/$target_filename"
  fi

  append_line_to_file "source $target_dir/$target_filename" "$1"
}

source_completion_file "$BASHRC"
source_completion_file "$ZSHRC"

append_line_to_file "source $CWD/aliases" "$HOME/.aliases"

symlink_to_home "$CWD/.tmux.conf"
symlink_to_home "$CWD/.tmuxinator"

