#!/bin/bash

set -e
source "$HOME/.functions"

if needs_install libnotify-bin notifyosdconfig; then
  info "adding patched notify-osd repository"
  apt_add_repository ppa:leolik/leolik

  info "adding patched notify-osd configuratation tool repository"
  apt_add_repository ppa:amandeepgrewal/notifyosdconfig

  apt_install libnotify-bin notifyosdconfig

  warn "killing running notify-osd"
  pkill notify-osd > /dev/null 2>&1
fi

CWD="$(get_script_dir "$0")"
symlink_to_home "$CWD/.notify-osd"
