#!/bin/bash

set -e
source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

# patched notify-osd
sudo add-apt-repository ppa:leolik/leolik
# configure patched notify-osd
sudo add-apt-repository ppa:amandeepgrewal/notifyosdconfig

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libnotify-bin notifyosdconfig

# kill running notify-osd
pkill notify-osd

symlink_to_home "$CWD/.notify-osd"
