#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "${BASH_SOURCE[0]}")"

if ! command -v git &> /dev/null; then
  sudo apt-add-repository ppa:git-core/ppa
  sudo apt-get update
  # git and meld (mergetool)
  sudo apt-get install git meld
else
  info "git is already installed"
fi

ln -fs "$CWD/.gitconfig" "$HOME"
ln -fs "$CWD/.gitignore_global" "$HOME"
