#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "${BASH_SOURCE[0]}")"

if ! command -v git &> /dev/null; then
  apt_add_repository git-core/ppa
  apt_install git-core
  #meld (mergetool)
  #sudo apt-get install -y meld
else
  debug "git is already installed"
fi

ln -fs "$CWD/.gitconfig" "$HOME"
ln -fs "$CWD/.gitignore_global" "$HOME"
