#!/bin/bash

set -e

source "$HOME/.functions"

if needs_install git git-core; then
  apt_add_repository ppa:git-core/ppa
  apt_install git-core
  #meld (mergetool)
  #sudo apt-get install -y meld
fi

CWD="$(get_script_dir "$0")"
symlink_to_home "$CWD/.gitconfig"
symlink_to_home "$CWD/.gitignore_global"
