#!/bin/bash

set -e

export LOGLEVEL=INFO
source "$HOME/.functions"
SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"

cd "$SCRIPT_DIR"

./clean
./restart > /dev/null 2>&1

pid="$(./wildfly-pid)"
while [ -z "$pid" ]; do
  pid="$(./wildfly-pid)"
  sleep 1
done
info "wildfly process running, pid : $pid"
