#!/bin/bash

export LOGLEVEL=INFO
source "$HOME/.functions"
SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"

cd "$SCRIPT_DIR"

./kill
./clean
sh "$WILDFLY_HOME/bin/standalone.sh" &>/dev/null &


pid="$(./wildfly-pid)"
while [ -z "$pid" ]; do
  pid="$(./wildfly-pid)"
  sleep 1
done
info "wildfly process running, pid : $pid"
