#!/bin/bash -l

source "$HOME/.functions"

get_pid() {
  cmdpid "java.*Standalone.*\-server.*[o]rg.jboss"
}

while true; do
  pid="$(get_pid)"

  if [ -z "$pid" ]; then
    echo "no existing process found"
    break
  fi

  echo "killing existing process with id $pid"
  kill -9 "$pid"
  sleep 1
done
