#!/bin/bash -l

export LOGLEVEL=INFO
source "$HOME/.functions"
cd "$(get_script_dir "${BASH_SOURCE[0]}")"

pid="$(./wildfly-pid)"
if [ -z "$pid" ]; then
  info "no existing process found"
else
  while [ ! -z "$(./wildfly-pid)" ]; do
    info "killing existing process with id $pid"
    kill -9 "$pid"
    sleep 1
  done
fi
exit 0
