#!/bin/bash -l

export LOGLEVEL=INFO
cd "$(dirname "$(readlink -sf "${BASH_SOURCE[0]}")")"

pid="$(./wildfly-pid)"
if [ -z "$pid" ]; then
  echo "no existing process found"
else
  while [ ! -z "$(./wildfly-pid)" ]; do
    echo "killing existing process with id $pid"
    kill -9 "$pid"
    sleep 1
  done
fi
exit 0
