#!/bin/bash


export LOGLEVEL=INFO
source "$HOME/.functions"
SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"

cd "$SCRIPT_DIR"
./kill
bash "$WILDFLY_HOME/bin/standalone.sh" > "$WILDFLY_HOME/standalone/log/all.log" 2>&1 &
