#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -sf "${BASH_SOURCE[0]}")")"

cd "$SCRIPT_DIR"
./kill
bash "$WILDFLY_HOME/bin/standalone.sh" > "$WILDFLY_HOME/standalone/log/all.log" & > /dev/null 2>&1

pid="$(./wildfly-pid)"
while [ -z "$pid" ]; do
  echo "wildfly process not up yet, sleeping"
  sleep 1
  pid="$(./wildfly-pid)"
done
echo "wildfly process running, pid : $pid"
