#!/bin/bash

source "$HOME/.functions"
SCRIPT_DIR="$(get_script_dir "$0")"

cd "$SCRIPT_DIR"
./kill
bash "$WILDFLY_HOME/bin/standalone.sh" > "$WILDFLY_HOME/standalone/log/all.log" & > /dev/null 2>&1

pid="$(./wildfly-pid)"
while [ -z "$pid" ]; do
  warn "wildfly process not up yet, sleeping"
  sleep 1
  pid="$(./wildfly-pid)"
done
info "wildfly process running, pid : $pid"
