#!/bin/bash

cd "$(dirname "$(readlink -sf "${BASH_SOURCE[0]}")")"
pid="$(./wildfly-pid)"

while [ -z "$pid" ]; do
  echo "wildfly is not running"
  sleep 5
  pid="$(./wildfly-pid)"
done

watch -d -t -n10 ./read-queues.py

