#!/bin/bash

set -e
source "$HOME/.functions"

CWD="$(get_script_dir "$0")"

packages=(mutt-patched libsecret-tools w3m urlview notmuch)
if needs_install "${packages[@]}"; then
  apt_install "${packages[@]}"
fi
# packages=(checkinstall autoconf libsecret-tools w3m urlview openssl libsasl2-modules libsasl2-dev libssl-dev libssl1.0.0 libnotmuch-dev notmuch libncurses5-dev libtokyocabinet-dev libkrb5-dev)
# if needs_install "${packages[@]}"; then
#   apt_install "${packages[@]}"
# fi

# NEOMUTT_TMP_INSTALL=/tmp/neomutt
# if needs_install neomutt; then
#   info "building neomutt from source"
#   if [ -d "$NEOMUTT_TMP_INSTALL" ]; then
#     rm -Rf "$NEOMUTT_TMP_INSTALL"
#   fi
#   git clone https://github.com/neomutt/neomutt "$NEOMUTT_TMP_INSTALL"

#   cd "$NEOMUTT_TMP_INSTALL"
#   ./prepare --enable-imap --enable-smtp --enable-sidebar --enable-notmuch --enable-hcache --with-gss --with-ssl --with-sasl
#   make && sudo checkinstall -y --pkgname=neomutt --pkgversion=1.6.2 --deldoc=yes --delspec=yes --deldesc=yes
#   cd "$CWD"
# fi

OFFLINEIMAP_TMP_INSTALL=/tmp/offlineimap
if needs_install offlineimap; then
  info "building offlineimap from source"
  if [ -d "$OFFLINEIMAP_TMP_INSTALL" ]; then
    rm -Rf "$OFFLINEIMAP_TMP_INSTALL"
  fi
  git clone https://github.com/OfflineIMAP/offlineimap "$OFFLINEIMAP_TMP_INSTALL"
  cd "$OFFLINEIMAP_TMP_INSTALL"
  make clean && make
  sudo python setup.py install
  cd "$CWD"
fi

if [ -t 1 -a ! -z "$DISPLAY" ]; then
	ACCOUNT="jonterje.kalvatn@gmail.com"
  SERVICE="mail"
	if ! secret-tool lookup "$SERVICE" "$ACCOUNT" > /dev/null; then
    info "storing password for $ACCOUNT (https://security.google.com/settings/security/apppasswords)"
		secret-tool store --label "$ACCOUNT" "$SERVICE" "$ACCOUNT"

		info "secret-tool lookup $SERVICE $ACCOUNT"
	else
		info "secret-tool lookup $SERVICE $ACCOUNT"
	fi

	ACCOUNT="j.kalvatn@sportradar.com"
	if ! secret-tool lookup "$SERVICE" "$ACCOUNT" > /dev/null; then
		info "storing password for $ACCOUNT"
		secret-tool store --label "$ACCOUNT" "$SERVICE" "$ACCOUNT"

		info "secret-tool lookup $SERVICE $ACCOUNT"
	else
		info "secret-tool lookup $SERVICE $ACCOUNT"
	fi
fi

symlink_to_home "$CWD/.mutt"
symlink_to_home "$CWD/.notmuch-config"
symlink_to_home "$CWD/.offlineimaprc"
