#!/bin/bash

# stolen from https://github.com/natmey/dotfiles/blob/master/notmuch/notmuch-post-sync

notmuch new
notmuch tag -unread -- from:j.kalvatn@sportradar.com
notmuch tag -unread -- from:jonterje.kalvatn@gmail.com

notmuch tag +intranet -- from:intranet@sportradar.com
notmuch tag +timesystem -- from:timesystem@sportradar.com
notmuch tag +jira -- from:jira@sportradar.com

NOTIFICATION_ICON=/usr/share/icons/gnome/24x24/emblems/emblem-mail.png
SEARCH="tag:unread"
#LIMIT=3
# SORT="newest-first"

UNREAD_COUNT=$(notmuch count --output=threads "$SEARCH")
if [ "$UNREAD_COUNT" -gt 0 ]; then
	# TXT_SUBS=$(notmuch search --format=text --output=summary --limit="$LIMIT" --sort="$SORT" "$SEARCH" | sed 's/^[^;]*; //' | sed 's/$/\n'/)
	# HTML_SUBS=$(echo "$TXT_SUBS" | recode UTF-8..html)
	# notify-send -i "$NOTIFICATION_ICON" "$UNREAD_COUNT unread mesages." "$HTML_SUBS"
  notify-send -i "$NOTIFICATION_ICON" "$UNREAD_COUNT unread emails."
fi
exit 0
