name: work
root: <%= ENV["PROJECTS"] %>

windows:
  - xmlexport:
      root: <%= ENV["PROJECTS"] + "/bac/xmlexport" %>
      layout: even-vertical
      panes:
        - git bst
  - java:
      root: <%= ENV["PROJECTS"] + "/bac/java" %>
      layout: even-vertical
      panes:
        - cd lib && git bst
        - cd source && git bst
  - www:
      root: <%= ENV["PROJECTS"] + "/dei" %>
      layout: even-vertical
      panes:
        - cd www && svn status
        - cd docker-shortcuts && git bst
  - puppet:
      root: <%= ENV["PROJECTS"] + "/sre" %>
      layout: even-vertical
      panes:
        - cd hiera-router && git bst
        - cd scripts && git bst
        - cd puppet && git bst
