#!/bin/bash

set -e

#./core-setup
#./vpn-setup

WORK_ROOT=/work
PROJECTS_ROOT="$WORK_ROOT/projects"

if [ ! -d "$WORK_ROOT" ]; then
  sudo mkdir "$WORK_ROOT"
  sudo chown -R kalvatn:kalvatn "$WORK_ROOT"
fi


mkdir -p "$WORK_ROOT/tools/ide/eclipse"
mkdir -p "$WORK_ROOT/tools/ide/eclipse/.metadata"
mkdir -p "$WORK_ROOT/tools/ide/intellij"


mkdir -p "$PROJECTS_ROOT/bac/java"
cd "$PROJECTS_ROOT/bac/java"
git clone git@git.sportradar.ag:java/source.git
git clone git@git.sportradar.ag:java/lib.git

#cd "$PROJECTS_ROOT/bac"
#git clone git@git.sportradar.ag:bac/xmlexport.git

#mkdir -p "$PROJECTS_ROOT/doc"
#git clone git@git.sportradar.ag:doc/documentation.git

#mkdir -p "$PROJECTS_ROOT/dei"
