#!/bin/bash

set -e

source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

packages=(mopidy mopidy-alsamixer mopidy-spotify mopidy-spotify-tunigo mopidy-scrobbler)
if needs_install "${packages[@]}"; then
  if sudo apt-key list | grep -q mopidy; then
    info "mopidy gpg already added"
  else
    info "adding mopidy gpg key"
    wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
  fi

  if [ -f /etc/apt/sources.list.d/mopidy.list ]; then
    info "mopidy list already added"
  else
    info "adding /etc/apt/sources.list.d/mopidy.list"
    sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/mopidy.list
    info "updating packages (quiet)"
    sudo apt-get update -qq
  fi
  apt_install "${packages[@]}"
else
  debug "${packages[*]} already installed"
fi


MOPIDY_CONF="$CWD/.config/mopidy/mopidy.conf"

if ! grep -q "SPOTIFY_USERNAME\|SPOTIFY_PASSWORD" "$MOPIDY_CONF"; then
  warn "enter SPOTIFY_USERNAME|PASSWORD"
  read -p   "SPOTIFY_USERNAME: " username
  read -sp  "SPOTIFY_PASSWORD: " password

  printf "\n"

  info "replacing SPOTIFY_USERNAME|PASSWORD placeholders in $MOPIDY_CONF"
  sed -i    "s/SPOTIFY_PASSWORD/$password/g" "$MOPIDY_CONF"
  sed -i    "s/SPOTIFY_USERNAME/$username/g" "$MOPIDY_CONF"
fi

if ! grep -q "LASTFM_USERNAME\|LASTFM_PASSWORD" "$MOPIDY_CONF"; then
  warn "enter LASTFM_USERNAME|PASSWORD"
  read -p   "LASTFM_USERNAME: " username
  read -sp  "LASTFM_PASSWORD: " password

  printf "\n"

  info "replacing LASTFM_USERNAME|PASSWORD placeholders in $MOPIDY_CONF"
  sed -i    "s/LASTFM_PASSWORD/$password/g" "$MOPIDY_CONF"
  sed -i    "s/LASTFM_USERNAME/$username/g" "$MOPIDY_CONF"
fi

mkdir -p "$HOME/.config/mopidy"
symlink "$CWD/.config/mopidy/mopidy.conf" "$HOME/.config/mopidy/mopidy.conf"




