- name: install steamcmd dependencies
  become: yes
  apt: pkg=lib32gcc1 state=latest

- name: create steamcmd home
  file: path="{{user_home}}/steamcmd" state=directory

- name: install steamcmd
  get_url:
    url: "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
    dest: "{{user_home}}/steamcmd"

- name: extract steamcmd
  unarchive: src="{{user_home}}/steamcmd/steamcmd_linux.tar.gz" dest="{{user_home}}/steamcmd"

- name: add murmur repo
  become: yes
  apt_repository: repo=ppa:mumble/release

- name: install murmur
  become: yes
  apt: pkg=mumble-server state=latest

- name: configure murmur
  become: yes
  command: dpkg-reconfigure mumble-server -f noninteractive

