
- name: install latest zsh package
  apt: pkg=zsh state=latest
  become: yes

- include: prezto.yml

- name: link zsh configuration
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
  with_items:
    - .zshrc

- name: change default login shell to zsh
  become: yes
  command: chsh -s /bin/zsh "{{user}}"
