
- name: install latest zsh package
  apt: pkg=zsh state=latest
  become: yes

- name: link zsh configuration
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "{{user_home}}/{{item}}"
    state: link
  with_items:
    - .zshrc
