- name: install prezto
  script: prezto-setup.sh creates="{{user_home}}/.zprezto"

- name: link prezto config
  file:
    src: "{{role_path}}/files/{{item.src}}"
    dest: "{{item.dest}}"
    state: link
    force: yes
  with_items:
    - { src: .zpreztorc, dest: "{{user_home}}/.zpreztorc" }
    - { src: prompt_kalvatn_setup, dest: "{{user_home}}/.zprezto/modules/prompt/functions/prompt_kalvatn_setup" }

- name: source prezto init file
  blockinfile:
    dest: "{{user_home}}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK .zpresto/init.zsh"
    follow: yes
    block: |
      ZPREZTO_INIT_FILE="${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
      if [ -s "$ZPREZTO_INIT_FILE" ]; then
        source "$ZPREZTO_INIT_FILE"
      fi


