#!/bin/bash

set -e
source "$HOME/.functions"
CWD="$(get_script_dir "$0")"

if needs_install i3; then
  apt_install i3
fi

ROFI_INSTALL_TMP=/tmp/rofi
if needs_install checkinstall rofi; then
  apt_install checkinstall

  # apt_install xcb-aux xcb-xkb xkbcommon xkbcommon-x11 xcb-ewmh xcb-xinerama xcb-icccm xcb-xrm
  apt_install libxcb-xkb-dev libxcb-xinerama0-dev  xkbcommon xkbcommon-x11 xcb-ewmh xcb-xinerama xcb-icccm xcb-xrm
  if [ ! -d "$ROFI_INSTALL_TMP" ]; then
    git clone https://github.com/DaveDavenport/rofi.git "$ROFI_INSTALL_TMP"
  fi
  cd "$ROFI_INSTALL_TMP"
  git clean -d -f
  git submodule update --init
  autoreconf -i
  mkdir -p build
  cd build
  ../configure
  make && sudo checkinstall -y --pkgname=rofi --pkgversion=1.6.2 --deldoc=yes --delspec=yes --deldesc=yes
fi

if needs_install i3blocks ruby-ronn; then
  apt_install ruby-ronn
  cd /tmp
  git clone git://github.com/vivien/i3blocks
  cd i3blocks
  make clean all
  sudo make install
fi

if needs_install xautolock mpstat sysstat acpi; then
  apt_install xautolock sysstat acpi
fi

symlink_to_home "$CWD/.i3"

if [ ! -z "$DISPLAY" ]; then
  connected_outputs="$(xrandr -q | grep -w connected | cut -d ' ' -f1)"
  if [ "$(echo "$connected_outputs" | wc -l)" -gt 1 ]; then
    debug "more than one connected outputs : $connected_outputs"
  else
    debug "only one connected output : $connected_outputs"
  fi
fi


if command_exists gsettings && [ ! -z "$DISPLAY" ]; then
  # fix nautilus desktop
  gsettings set "org.gnome.desktop.background" "show-desktop-icons" false > /dev/null 2>&1
fi
