#!/bin/bash

set -e
source "$HOME/.functions"

if needs_install npm; then
  error "run npm setup first"
  exit 1
fi

if needs_install castnow; then
  info "installing castnow"
  sudo npm install castnow -g
fi
