#!/bin/bash

set -e

source "$HOME/.functions"

if needs_install zsh; then
  apt_install zsh
fi

CWD="$(get_script_dir "$0")"
symlink_to_home "$CWD/.zshrc"
symlink_to_home "$CWD/.oh-my-zsh"
symlink "$CWD/oh-my-zsh-custom-themes/kalvatn.zsh-theme" "$HOME/.oh-my-zsh/themes/"

current_shell="$(getent passwd "$USER" | cut -d: -f7)"
if [ "$current_shell" != "/bin/zsh" ]; then
  info "setting default shell to /bin/zsh for user $USER"
  sudo chsh -s /bin/zsh kalvatn
else
  debug "/bin/zsh is already the default shell"
fi
