#!/bin/bash

source "$HOME/.functions"

if needs_install spotify spotify-client; then
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
  apt_add_repository "deb http://repository.spotify.com stable non-free"
  apt_install spotify-client
fi

