#!/bin/bash

set -e
source "$HOME/.functions"

if needs_install google-chrome google-chrome-stable; then
  if ! apt_has_key google; then
    # http://www.ubuntuupdates.org/ppa/google_chrome
    info "adding google_chrome gpg key"
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  fi

  if [ -f /etc/apt/sources.list.d/google.list -o -f /etc/apt/sources.list.d/google-chrome.list ]; then
    info "google_chrome list already added"
  else
    info "adding /etc/apt/sources.list.d/google.list"
    sudo bash -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    info "updating packages (quiet)"
    sudo apt-get update -qq
  fi
  apt_install google-chrome-stable
fi


