#!/bin/bash

set -e
source "$HOME/.functions"

if needs_install pipelight-plugin; then
  apt_add_repository pipelight/stable
  apt_install --install-recommends pipelight-multi
fi

info "enabling pipelight-plugins"
sudo pipelight-plugin --enable flash
sudo pipelight-plugin --enable widevine
sudo pipelight-plugin --enable silverlight

info "update/create pipelight mozilla plugins"
sudo pipelight-plugin --update
sudo pipelight-plugin --create-mozilla-plugins

