#!/bin/bash

set -e
source "$HOME/.functions"


#class unifocus-context::msfonts {
#  exec { "accept-msttcorefonts-license":
#    command => "/bin/sh -c \"echo ttf-mscorefonts-installer msttcorefonts/accepted-     mscorefonts-eula select true | debconf-set-selections\""
#  }
#
#  package { "msttcorefonts":
#    ensure  => installed,
#    require => Exec['accept-msttcorefonts-license']
#  }
#}

if needs_install pipelight-plugin; then

  apt_add_repository ppa:pipelight/stable
  if [ "$(sudo dpkg --print-architecture)" == "amd64" -a -z "$(sudo dpkg --print-foreign-architectures)" ]; then
    # wine requires i386 libs
    sudo dpkg --add-architecture i386
    sudo apt-get update -qq
  fi

  if needs_install ttf-mscorefonts-installer; then
    apt_add_repository multiverse
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    apt_install ttf-mscorefonts-installer
  fi
  #apt_install --install-recommends pipelight-multi wine-staging
  sudo apt-get install -y --install-recommends pipelight-multi wine-staging
  info "enabling pipelight-plugins"
  if ! pipelight-plugin --list-enabled-all | grep -q "flash"; then
    sudo pipelight-plugin --accept --enable flash
  fi
  if ! pipelight-plugin --list-enabled-all | grep -q "widevine"; then
    sudo pipelight-plugin --accept --enable widevine
  fi
  if ! pipelight-plugin --list-enabled-all | grep -q "silverlight"; then
    sudo pipelight-plugin --accept --enable silverlight
  fi

  info "update/create pipelight mozilla plugins"
  sudo pipelight-plugin --update
  sudo pipelight-plugin --create-mozilla-plugins
fi


