- name: add oracle-java-8 repository
  become: yes
  apt_repository: repo="ppa:webupd8team/java"

- name: accept license
  become: yes
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install oracle-java8-installer
  become: yes
  apt: pkg=oracle-java8-installer state=latest

- name: install maven
  become: yes
  apt: pkg=maven state=latest
