---

# if needs_install spotify spotify-client; then
#   sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
#   apt_add_repository "deb http://repository.spotify.com stable non-free"
#   apt_install spotify-client
# fi
- name: add spotify key
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: add spotify repository
  become: yes
  apt_repository: repo="deb http://repository.spotify.com stable non-free"

- name: install spotify client
  become: yes
  apt: pkg=spotify-client state=latest
